### PR TITLE
Adding support for phpstan

### PR DESCRIPTION
**Pull request by pnx**
Nice to have phpstan in this project to catch additional problems :)

### CODE REVIEW

**Comment by olssonm** [comment]
@pnx Thanks! Haven't worked much with PHPStan to be honest, will look through it all as soon as I've got the time!

**Comment by verifiera** [comment]
PHPDoc does not follow convention:
https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/property.html

There is a $ sign in front of variable names in @property tag (all tags actually). PHPStorm allows variables without $, but this is not correct.

**Comment by verifiera** [comment]
> PHPDoc does not follow convention: https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/property.html
> 
> There is a $ sign in front of variable names in @Property tag (all tags actually). PHPStorm allows variables without $, but this is not correct.

For example in Refund.php

**Comment by olssonm** [comment]
@verifiera – not sure what you mean? This PR by @pnx's adds `$` for `@property`?

**Comment by verifiera** [comment]
> @verifiera – not sure what you mean? This PR by @pnx's adds `$` for `@property`?

PR does it also. Just wanted to say that to make it easy to use your great library in a project with PHPStan static analysis probably is enough to update @phpDocs for Olssonm\Swish\Refund (other classes looks correctly). Currently, there is a problem, we use your library in the project with phpstan integrated, and need handle the Refund class in a special way because $ signs are missing in @phpDoc section.

**Comment by olssonm** [comment]
@pnx Thanks for your PR! A new release has been published ([v2.1](https://github.com/olssonm/swish-php/releases/tag/v2.1)) and it should be available shortly via [packagist.org](https://packagist.org/packages/olssonm/swish-php).

**Comment by verifiera** [comment]
👍

**Pull request merged**
